name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Java maven library publisher
      uses: MathieuSoysal/Java-maven-library-publisher@v1.0.3
      with:      
        nexus-username: ${{ secrets.NEXUS_USERNAME }}
        nexus-password: ${{ secrets.NEXUS_PASSWORD }}
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        java-version: 11
